apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grantclaw.fullname" . }}
  labels:
    {{- include "grantclaw.labels" . | nindent 4 }}
data:
  {{- $botfiles := .Files.Glob "botfiles/*" }}
  {{- if $botfiles }}
  {{- range $path, $content := $botfiles }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
  {{- end }}
  {{- else }}
  config.yaml: |
    {{- .Values.bot.config | nindent 4 }}
  {{- range $name, $content := .Values.bot.files }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- end }}
---
{{- $toolfiles := .Files.Glob "botfiles/tools/*" }}
{{- if or $toolfiles .Values.bot.tools }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grantclaw.fullname" . }}-tools
  labels:
    {{- include "grantclaw.labels" . | nindent 4 }}
data:
  {{- if $toolfiles }}
  {{- range $path, $content := $toolfiles }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- range $name, $content := .Values.bot.tools }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- $docfiles := .Files.Glob "botfiles/docs/*" }}
{{- if or $docfiles .Values.bot.docs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grantclaw.fullname" . }}-docs
  labels:
    {{- include "grantclaw.labels" . | nindent 4 }}
data:
  {{- if $docfiles }}
  {{- range $path, $content := $docfiles }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- range $name, $content := .Values.bot.docs }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
